### ISSUE TITLE
Needs a better distribution mechanism

### ISSUE THREAD

**Issue by aaroncrespo** [RLovelett/node-sourcekit#5]
I don't currently have a compiled swift toolchain set which means installing the node.js package fails when compiling the plugin: missing `#include "sourcekitd/sourcekitd.h"`

I don't think we should expect users to need a compiled toolchain.

Most of the initial work of creating the typescript types is getting setup on the registry. But that requires being able to install node-sourcekit from NPM.

Maybe this is fine if under Xcode8 and swift3 the header is visible, but on Xcode 7 it's not.

**Comment by RLovelett** [comment]
I agree. It does not look like it is going to go out in Xcode 8 either.

[I asked about this on the mailing lists](https://lists.swift.org/pipermail/swift-dev/Week-of-Mon-20160808/002643.html). While I disagree with the outcome I can appreciate their position.

With all of that having been said. What should this project do? Well I think we are going to have to bundle the headers with project and then link against the default toolchain bundled with the developers chosen Xcode (e.g., `xcode-select`).

**Comment by RLovelett** [comment]
My biggest concern right now is licensing. [The header is licensed as Apache](https://github.com/apple/swift/blob/e5ea766e99f0693b359dd3b689c46f0fd6847f6b/tools/SourceKit/tools/sourcekitd/include/sourcekitd/sourcekitd.h#L1-L11).

I had planned to release this as [MIT](https://github.com/RLovelett/node-sourcekit/blob/be699f5972a65ae5aafce36a6351f9bb4be810ac/LICENSE). IANAL and because of that I usually try to stay clear of mixing licenses.

So do you know what the guidance/rules/best-practices regarding this are?

**Comment by RLovelett** [comment]
Fixed by https://github.com/RLovelett/node-sourcekit/pull/7
